// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package client

import (
	"context"
)

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, auth_method, is_admin, created_at, updated_at FROM accounts WHERE username = ?
`

// Retrieves sitewide account for login authentication
func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AuthMethod,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommitteeBySlug = `-- name: GetCommitteeBySlug :one
SELECT id, name, slug, created_at, updated_at, current_meeting_id FROM committees WHERE slug = ?
`

// Retrieves committee by slug
func (q *Queries) GetCommitteeBySlug(ctx context.Context, slug string) (Committee, error) {
	row := q.db.QueryRowContext(ctx, getCommitteeBySlug, slug)
	var i Committee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentMeetingID,
	)
	return i, err
}

const getPasswordCredentialByAccountID = `-- name: GetPasswordCredentialByAccountID :one
SELECT id, account_id, auth_method, password_hash, created_at, updated_at FROM password_credentials WHERE account_id = ?
`

// Retrieves the password credential for a given account
func (q *Queries) GetPasswordCredentialByAccountID(ctx context.Context, accountID int64) (PasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, getPasswordCredentialByAccountID, accountID)
	var i PasswordCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AuthMethod,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.account_id, u.committee_id, u.full_name, u.role, u.quoted,
       u.created_at, u.updated_at, a.username
FROM users u
JOIN accounts a ON u.account_id = a.id
WHERE u.id = ?
`

type GetUserByIDRow struct {
	ID          int64
	AccountID   int64
	CommitteeID int64
	FullName    string
	Role        string
	Quoted      bool
	CreatedAt   string
	UpdatedAt   string
	Username    string
}

// Retrieves membership row by ID (for session restoration), including username from accounts
func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CommitteeID,
		&i.FullName,
		&i.Role,
		&i.Quoted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getUserMembershipByAccountAndCommittee = `-- name: GetUserMembershipByAccountAndCommittee :one
SELECT u.id, u.account_id, u.committee_id, u.full_name, u.role, u.quoted,
       u.created_at, u.updated_at, a.username
FROM users u
JOIN accounts a ON u.account_id = a.id
JOIN committees c ON u.committee_id = c.id
WHERE a.username = ? AND c.slug = ?
`

type GetUserMembershipByAccountAndCommitteeParams struct {
	Username string
	Slug     string
}

type GetUserMembershipByAccountAndCommitteeRow struct {
	ID          int64
	AccountID   int64
	CommitteeID int64
	FullName    string
	Role        string
	Quoted      bool
	CreatedAt   string
	UpdatedAt   string
	Username    string
}

// Retrieves the committee membership row for an account+committee combination,
// including the username from the accounts table.
func (q *Queries) GetUserMembershipByAccountAndCommittee(ctx context.Context, arg GetUserMembershipByAccountAndCommitteeParams) (GetUserMembershipByAccountAndCommitteeRow, error) {
	row := q.db.QueryRowContext(ctx, getUserMembershipByAccountAndCommittee, arg.Username, arg.Slug)
	var i GetUserMembershipByAccountAndCommitteeRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CommitteeID,
		&i.FullName,
		&i.Role,
		&i.Quoted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}
