// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blobs.sql

package client

import (
	"context"
)

const createBinaryBlob = `-- name: CreateBinaryBlob :one
INSERT INTO binary_blobs (filename, content_type, size_bytes, storage_path)
VALUES (?, ?, ?, ?)
RETURNING id, filename, content_type, size_bytes, storage_path, created_at
`

type CreateBinaryBlobParams struct {
	Filename    string
	ContentType string
	SizeBytes   int64
	StoragePath string
}

func (q *Queries) CreateBinaryBlob(ctx context.Context, arg CreateBinaryBlobParams) (BinaryBlob, error) {
	row := q.db.QueryRowContext(ctx, createBinaryBlob,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StoragePath,
	)
	var i BinaryBlob
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBinaryBlob = `-- name: DeleteBinaryBlob :exec
DELETE FROM binary_blobs WHERE id = ?
`

func (q *Queries) DeleteBinaryBlob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBinaryBlob, id)
	return err
}

const getBinaryBlobByID = `-- name: GetBinaryBlobByID :one
SELECT id, filename, content_type, size_bytes, storage_path, created_at
FROM binary_blobs WHERE id = ?
`

func (q *Queries) GetBinaryBlobByID(ctx context.Context, id int64) (BinaryBlob, error) {
	row := q.db.QueryRowContext(ctx, getBinaryBlobByID, id)
	var i BinaryBlob
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}
