// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package client

import (
	"database/sql"
)

type AgendaAttachment struct {
	ID            int64
	AgendaPointID int64
	BlobID        int64
	Label         sql.NullString
	CreatedAt     string
}

type AgendaPoint struct {
	ID               int64
	MeetingID        int64
	ParentID         sql.NullInt64
	Position         int64
	Title            string
	Protocol         string
	CreatedAt        string
	UpdatedAt        string
	CurrentSpeakerID sql.NullInt64
}

type BinaryBlob struct {
	ID          int64
	Filename    string
	ContentType string
	SizeBytes   int64
	StoragePath string
	CreatedAt   string
}

type Committee struct {
	ID               int64
	Name             string
	CreatedAt        string
	UpdatedAt        string
	CurrentMeetingID sql.NullInt64
}

type Meeting struct {
	ID                   int64
	CommitteeID          int64
	Name                 string
	Description          string
	CreatedAt            string
	UpdatedAt            string
	CurrentAgendaPointID sql.NullInt64
}

type Motion struct {
	ID             int64
	AgendaPointID  int64
	BlobID         int64
	Title          string
	VotesFor       sql.NullInt64
	VotesAgainst   sql.NullInt64
	VotesAbstained sql.NullInt64
	VotesEligible  sql.NullInt64
	CreatedAt      string
	UpdatedAt      string
}

type SpeakersList struct {
	ID            int64
	AgendaPointID int64
	UserID        int64
	Type          string
	Status        string
	RequestedAt   string
	StartOfSpeech sql.NullString
	Duration      sql.NullString
}

type User struct {
	ID           int64
	CommitteeID  int64
	Username     string
	PasswordHash string
	FullName     string
	Gender       string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}
