// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: votes.sql

package client

import (
	"context"
	"database/sql"
)

const countEligibleVotersForVoteDefinition = `-- name: CountEligibleVotersForVoteDefinition :one
SELECT COUNT(*) FROM eligible_voters WHERE vote_definition_id = ?
`

func (q *Queries) CountEligibleVotersForVoteDefinition(ctx context.Context, voteDefinitionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEligibleVotersForVoteDefinition, voteDefinitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecretVoteBallots = `-- name: CountSecretVoteBallots :one
SELECT COUNT(*)
FROM vote_ballots
WHERE vote_definition_id = ? AND attendee_id IS NULL
`

func (q *Queries) CountSecretVoteBallots(ctx context.Context, voteDefinitionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSecretVoteBallots, voteDefinitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVoteCastsForVoteDefinition = `-- name: CountVoteCastsForVoteDefinition :one
SELECT COUNT(*)
FROM vote_casts
WHERE vote_definition_id = ?
`

func (q *Queries) CountVoteCastsForVoteDefinition(ctx context.Context, voteDefinitionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVoteCastsForVoteDefinition, voteDefinitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOpenVoteBallot = `-- name: CreateOpenVoteBallot :one
INSERT INTO vote_ballots (vote_definition_id, cast_id, attendee_id, receipt_token)
VALUES (?, ?, ?, ?)
RETURNING id, vote_definition_id, cast_id, attendee_id, receipt_token, encrypted_commitment, commitment_cipher, commitment_version, created_at
`

type CreateOpenVoteBallotParams struct {
	VoteDefinitionID int64
	CastID           sql.NullInt64
	AttendeeID       sql.NullInt64
	ReceiptToken     string
}

func (q *Queries) CreateOpenVoteBallot(ctx context.Context, arg CreateOpenVoteBallotParams) (VoteBallot, error) {
	row := q.db.QueryRowContext(ctx, createOpenVoteBallot,
		arg.VoteDefinitionID,
		arg.CastID,
		arg.AttendeeID,
		arg.ReceiptToken,
	)
	var i VoteBallot
	err := row.Scan(
		&i.ID,
		&i.VoteDefinitionID,
		&i.CastID,
		&i.AttendeeID,
		&i.ReceiptToken,
		&i.EncryptedCommitment,
		&i.CommitmentCipher,
		&i.CommitmentVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createSecretVoteBallot = `-- name: CreateSecretVoteBallot :one
INSERT INTO vote_ballots (
    vote_definition_id, cast_id, attendee_id, receipt_token, encrypted_commitment, commitment_cipher, commitment_version
)
VALUES (?, NULL, NULL, ?, ?, ?, ?)
RETURNING id, vote_definition_id, cast_id, attendee_id, receipt_token, encrypted_commitment, commitment_cipher, commitment_version, created_at
`

type CreateSecretVoteBallotParams struct {
	VoteDefinitionID    int64
	ReceiptToken        string
	EncryptedCommitment []byte
	CommitmentCipher    sql.NullString
	CommitmentVersion   sql.NullInt64
}

func (q *Queries) CreateSecretVoteBallot(ctx context.Context, arg CreateSecretVoteBallotParams) (VoteBallot, error) {
	row := q.db.QueryRowContext(ctx, createSecretVoteBallot,
		arg.VoteDefinitionID,
		arg.ReceiptToken,
		arg.EncryptedCommitment,
		arg.CommitmentCipher,
		arg.CommitmentVersion,
	)
	var i VoteBallot
	err := row.Scan(
		&i.ID,
		&i.VoteDefinitionID,
		&i.CastID,
		&i.AttendeeID,
		&i.ReceiptToken,
		&i.EncryptedCommitment,
		&i.CommitmentCipher,
		&i.CommitmentVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createVoteBallotSelection = `-- name: CreateVoteBallotSelection :exec
INSERT INTO vote_ballot_selections (ballot_id, vote_definition_id, option_id)
VALUES (?, ?, ?)
`

type CreateVoteBallotSelectionParams struct {
	BallotID         int64
	VoteDefinitionID int64
	OptionID         int64
}

func (q *Queries) CreateVoteBallotSelection(ctx context.Context, arg CreateVoteBallotSelectionParams) error {
	_, err := q.db.ExecContext(ctx, createVoteBallotSelection, arg.BallotID, arg.VoteDefinitionID, arg.OptionID)
	return err
}

const createVoteCast = `-- name: CreateVoteCast :one
INSERT INTO vote_casts (vote_definition_id, meeting_id, attendee_id, source)
VALUES (?, ?, ?, ?)
RETURNING id, vote_definition_id, meeting_id, attendee_id, source, created_at
`

type CreateVoteCastParams struct {
	VoteDefinitionID int64
	MeetingID        int64
	AttendeeID       int64
	Source           string
}

func (q *Queries) CreateVoteCast(ctx context.Context, arg CreateVoteCastParams) (VoteCast, error) {
	row := q.db.QueryRowContext(ctx, createVoteCast,
		arg.VoteDefinitionID,
		arg.MeetingID,
		arg.AttendeeID,
		arg.Source,
	)
	var i VoteCast
	err := row.Scan(
		&i.ID,
		&i.VoteDefinitionID,
		&i.MeetingID,
		&i.AttendeeID,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createVoteDefinition = `-- name: CreateVoteDefinition :one
INSERT INTO vote_definitions (
    meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections
)
VALUES (?, ?, ?, ?, ?, 'draft', ?, ?)
RETURNING id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at
`

type CreateVoteDefinitionParams struct {
	MeetingID     int64
	AgendaPointID int64
	MotionID      sql.NullInt64
	Name          string
	Visibility    string
	MinSelections int64
	MaxSelections int64
}

func (q *Queries) CreateVoteDefinition(ctx context.Context, arg CreateVoteDefinitionParams) (VoteDefinition, error) {
	row := q.db.QueryRowContext(ctx, createVoteDefinition,
		arg.MeetingID,
		arg.AgendaPointID,
		arg.MotionID,
		arg.Name,
		arg.Visibility,
		arg.MinSelections,
		arg.MaxSelections,
	)
	var i VoteDefinition
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgendaPointID,
		&i.MotionID,
		&i.Name,
		&i.Visibility,
		&i.State,
		&i.MinSelections,
		&i.MaxSelections,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoteOption = `-- name: CreateVoteOption :one
INSERT INTO vote_options (vote_definition_id, label, position)
VALUES (?, ?, ?)
RETURNING id, vote_definition_id, label, position, created_at
`

type CreateVoteOptionParams struct {
	VoteDefinitionID int64
	Label            string
	Position         int64
}

func (q *Queries) CreateVoteOption(ctx context.Context, arg CreateVoteOptionParams) (VoteOption, error) {
	row := q.db.QueryRowContext(ctx, createVoteOption, arg.VoteDefinitionID, arg.Label, arg.Position)
	var i VoteOption
	err := row.Scan(
		&i.ID,
		&i.VoteDefinitionID,
		&i.Label,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVoteOptionsForVoteDefinition = `-- name: DeleteVoteOptionsForVoteDefinition :exec
DELETE FROM vote_options WHERE vote_definition_id = ?
`

func (q *Queries) DeleteVoteOptionsForVoteDefinition(ctx context.Context, voteDefinitionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteVoteOptionsForVoteDefinition, voteDefinitionID)
	return err
}

const getOpenVoteVerificationRows = `-- name: GetOpenVoteVerificationRows :many
SELECT
    vd.id            AS vote_definition_id,
    vd.name          AS vote_name,
    a.id             AS attendee_id,
    a.attendee_number,
    vb.receipt_token,
    vo.id            AS option_id,
    vo.label         AS option_label
FROM vote_ballots vb
JOIN vote_definitions vd ON vd.id = vb.vote_definition_id
JOIN attendees a ON a.id = vb.attendee_id
LEFT JOIN vote_ballot_selections vbs ON vbs.ballot_id = vb.id AND vbs.vote_definition_id = vb.vote_definition_id
LEFT JOIN vote_options vo ON vo.id = vbs.option_id AND vo.vote_definition_id = vb.vote_definition_id
WHERE vb.vote_definition_id = ? AND vb.receipt_token = ? AND vb.attendee_id IS NOT NULL
ORDER BY vo.position ASC, vo.id ASC
`

type GetOpenVoteVerificationRowsParams struct {
	VoteDefinitionID int64
	ReceiptToken     string
}

type GetOpenVoteVerificationRowsRow struct {
	VoteDefinitionID int64
	VoteName         string
	AttendeeID       int64
	AttendeeNumber   sql.NullInt64
	ReceiptToken     string
	OptionID         sql.NullInt64
	OptionLabel      sql.NullString
}

func (q *Queries) GetOpenVoteVerificationRows(ctx context.Context, arg GetOpenVoteVerificationRowsParams) ([]GetOpenVoteVerificationRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOpenVoteVerificationRows, arg.VoteDefinitionID, arg.ReceiptToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpenVoteVerificationRowsRow
	for rows.Next() {
		var i GetOpenVoteVerificationRowsRow
		if err := rows.Scan(
			&i.VoteDefinitionID,
			&i.VoteName,
			&i.AttendeeID,
			&i.AttendeeNumber,
			&i.ReceiptToken,
			&i.OptionID,
			&i.OptionLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSecretVoteVerification = `-- name: GetSecretVoteVerification :one
SELECT
    vd.id                 AS vote_definition_id,
    vd.name               AS vote_name,
    vb.receipt_token,
    vb.encrypted_commitment,
    vb.commitment_cipher,
    vb.commitment_version
FROM vote_ballots vb
JOIN vote_definitions vd ON vd.id = vb.vote_definition_id
WHERE vb.vote_definition_id = ? AND vb.receipt_token = ? AND vb.attendee_id IS NULL
LIMIT 1
`

type GetSecretVoteVerificationParams struct {
	VoteDefinitionID int64
	ReceiptToken     string
}

type GetSecretVoteVerificationRow struct {
	VoteDefinitionID    int64
	VoteName            string
	ReceiptToken        string
	EncryptedCommitment []byte
	CommitmentCipher    sql.NullString
	CommitmentVersion   sql.NullInt64
}

func (q *Queries) GetSecretVoteVerification(ctx context.Context, arg GetSecretVoteVerificationParams) (GetSecretVoteVerificationRow, error) {
	row := q.db.QueryRowContext(ctx, getSecretVoteVerification, arg.VoteDefinitionID, arg.ReceiptToken)
	var i GetSecretVoteVerificationRow
	err := row.Scan(
		&i.VoteDefinitionID,
		&i.VoteName,
		&i.ReceiptToken,
		&i.EncryptedCommitment,
		&i.CommitmentCipher,
		&i.CommitmentVersion,
	)
	return i, err
}

const getVoteCastByVoteAndAttendee = `-- name: GetVoteCastByVoteAndAttendee :one
SELECT id, vote_definition_id, meeting_id, attendee_id, source, created_at
FROM vote_casts
WHERE vote_definition_id = ? AND attendee_id = ?
`

type GetVoteCastByVoteAndAttendeeParams struct {
	VoteDefinitionID int64
	AttendeeID       int64
}

func (q *Queries) GetVoteCastByVoteAndAttendee(ctx context.Context, arg GetVoteCastByVoteAndAttendeeParams) (VoteCast, error) {
	row := q.db.QueryRowContext(ctx, getVoteCastByVoteAndAttendee, arg.VoteDefinitionID, arg.AttendeeID)
	var i VoteCast
	err := row.Scan(
		&i.ID,
		&i.VoteDefinitionID,
		&i.MeetingID,
		&i.AttendeeID,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteDefinitionByID = `-- name: GetVoteDefinitionByID :one
SELECT id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at FROM vote_definitions WHERE id = ?
`

func (q *Queries) GetVoteDefinitionByID(ctx context.Context, id int64) (VoteDefinition, error) {
	row := q.db.QueryRowContext(ctx, getVoteDefinitionByID, id)
	var i VoteDefinition
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgendaPointID,
		&i.MotionID,
		&i.Name,
		&i.Visibility,
		&i.State,
		&i.MinSelections,
		&i.MaxSelections,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoteSubmissionStats = `-- name: GetVoteSubmissionStats :one
SELECT
    (SELECT COUNT(*) FROM eligible_voters ev WHERE ev.vote_definition_id = ?) AS eligible_count,
    (SELECT COUNT(*) FROM vote_casts vc WHERE vc.vote_definition_id = ?) AS cast_count,
    (SELECT COUNT(*) FROM vote_ballots vb WHERE vb.vote_definition_id = ?) AS ballot_count,
    (SELECT COUNT(*) FROM vote_ballots vb WHERE vb.vote_definition_id = ? AND vb.attendee_id IS NOT NULL) AS open_ballot_count,
    (SELECT COUNT(*) FROM vote_ballots vb WHERE vb.vote_definition_id = ? AND vb.attendee_id IS NULL) AS secret_ballot_count
`

type GetVoteSubmissionStatsParams struct {
	VoteDefinitionID   int64
	VoteDefinitionID_2 int64
	VoteDefinitionID_3 int64
	VoteDefinitionID_4 int64
	VoteDefinitionID_5 int64
}

type GetVoteSubmissionStatsRow struct {
	EligibleCount     int64
	CastCount         int64
	BallotCount       int64
	OpenBallotCount   int64
	SecretBallotCount int64
}

func (q *Queries) GetVoteSubmissionStats(ctx context.Context, arg GetVoteSubmissionStatsParams) (GetVoteSubmissionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getVoteSubmissionStats,
		arg.VoteDefinitionID,
		arg.VoteDefinitionID_2,
		arg.VoteDefinitionID_3,
		arg.VoteDefinitionID_4,
		arg.VoteDefinitionID_5,
	)
	var i GetVoteSubmissionStatsRow
	err := row.Scan(
		&i.EligibleCount,
		&i.CastCount,
		&i.BallotCount,
		&i.OpenBallotCount,
		&i.SecretBallotCount,
	)
	return i, err
}

const getVoteTallies = `-- name: GetVoteTallies :many
SELECT
    vo.id AS option_id,
    vo.label AS option_label,
    CAST(COALESCE(COUNT(vbs.option_id), 0) AS INTEGER) AS tally_count
FROM vote_options vo
LEFT JOIN vote_ballot_selections vbs ON vbs.option_id = vo.id AND vbs.vote_definition_id = vo.vote_definition_id
WHERE vo.vote_definition_id = ?
GROUP BY vo.id, vo.label, vo.position
ORDER BY vo.position ASC, vo.id ASC
`

type GetVoteTalliesRow struct {
	OptionID    int64
	OptionLabel string
	TallyCount  int64
}

func (q *Queries) GetVoteTallies(ctx context.Context, voteDefinitionID int64) ([]GetVoteTalliesRow, error) {
	rows, err := q.db.QueryContext(ctx, getVoteTallies, voteDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVoteTalliesRow
	for rows.Next() {
		var i GetVoteTalliesRow
		if err := rows.Scan(&i.OptionID, &i.OptionLabel, &i.TallyCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEligibleVoter = `-- name: InsertEligibleVoter :exec
INSERT INTO eligible_voters (vote_definition_id, meeting_id, attendee_id)
VALUES (?, ?, ?)
`

type InsertEligibleVoterParams struct {
	VoteDefinitionID int64
	MeetingID        int64
	AttendeeID       int64
}

func (q *Queries) InsertEligibleVoter(ctx context.Context, arg InsertEligibleVoterParams) error {
	_, err := q.db.ExecContext(ctx, insertEligibleVoter, arg.VoteDefinitionID, arg.MeetingID, arg.AttendeeID)
	return err
}

const listEligibleVotersForVoteDefinition = `-- name: ListEligibleVotersForVoteDefinition :many
SELECT vote_definition_id, meeting_id, attendee_id, created_at
FROM eligible_voters
WHERE vote_definition_id = ?
ORDER BY attendee_id ASC
`

func (q *Queries) ListEligibleVotersForVoteDefinition(ctx context.Context, voteDefinitionID int64) ([]EligibleVoter, error) {
	rows, err := q.db.QueryContext(ctx, listEligibleVotersForVoteDefinition, voteDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EligibleVoter
	for rows.Next() {
		var i EligibleVoter
		if err := rows.Scan(
			&i.VoteDefinitionID,
			&i.MeetingID,
			&i.AttendeeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoteCastsForVoteDefinition = `-- name: ListVoteCastsForVoteDefinition :many
SELECT id, vote_definition_id, meeting_id, attendee_id, source, created_at
FROM vote_casts
WHERE vote_definition_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListVoteCastsForVoteDefinition(ctx context.Context, voteDefinitionID int64) ([]VoteCast, error) {
	rows, err := q.db.QueryContext(ctx, listVoteCastsForVoteDefinition, voteDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoteCast
	for rows.Next() {
		var i VoteCast
		if err := rows.Scan(
			&i.ID,
			&i.VoteDefinitionID,
			&i.MeetingID,
			&i.AttendeeID,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoteDefinitionsForAgendaPoint = `-- name: ListVoteDefinitionsForAgendaPoint :many
SELECT id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at
FROM vote_definitions
WHERE agenda_point_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListVoteDefinitionsForAgendaPoint(ctx context.Context, agendaPointID int64) ([]VoteDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listVoteDefinitionsForAgendaPoint, agendaPointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoteDefinition
	for rows.Next() {
		var i VoteDefinition
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.AgendaPointID,
			&i.MotionID,
			&i.Name,
			&i.Visibility,
			&i.State,
			&i.MinSelections,
			&i.MaxSelections,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoteOptionIDsForVoteDefinition = `-- name: ListVoteOptionIDsForVoteDefinition :many
SELECT id
FROM vote_options
WHERE vote_definition_id = ?
`

func (q *Queries) ListVoteOptionIDsForVoteDefinition(ctx context.Context, voteDefinitionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listVoteOptionIDsForVoteDefinition, voteDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoteOptionsForVoteDefinition = `-- name: ListVoteOptionsForVoteDefinition :many
SELECT id, vote_definition_id, label, position, created_at
FROM vote_options
WHERE vote_definition_id = ?
ORDER BY position ASC, id ASC
`

func (q *Queries) ListVoteOptionsForVoteDefinition(ctx context.Context, voteDefinitionID int64) ([]VoteOption, error) {
	rows, err := q.db.QueryContext(ctx, listVoteOptionsForVoteDefinition, voteDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoteOption
	for rows.Next() {
		var i VoteOption
		if err := rows.Scan(
			&i.ID,
			&i.VoteDefinitionID,
			&i.Label,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVoteDefinitionArchived = `-- name: SetVoteDefinitionArchived :one
UPDATE vote_definitions
SET state = 'archived',
    archived_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'closed'
RETURNING id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at
`

func (q *Queries) SetVoteDefinitionArchived(ctx context.Context, id int64) (VoteDefinition, error) {
	row := q.db.QueryRowContext(ctx, setVoteDefinitionArchived, id)
	var i VoteDefinition
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgendaPointID,
		&i.MotionID,
		&i.Name,
		&i.Visibility,
		&i.State,
		&i.MinSelections,
		&i.MaxSelections,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setVoteDefinitionClosedFromCounting = `-- name: SetVoteDefinitionClosedFromCounting :one
UPDATE vote_definitions
SET state = 'closed',
    closed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'counting'
RETURNING id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at
`

func (q *Queries) SetVoteDefinitionClosedFromCounting(ctx context.Context, id int64) (VoteDefinition, error) {
	row := q.db.QueryRowContext(ctx, setVoteDefinitionClosedFromCounting, id)
	var i VoteDefinition
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgendaPointID,
		&i.MotionID,
		&i.Name,
		&i.Visibility,
		&i.State,
		&i.MinSelections,
		&i.MaxSelections,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setVoteDefinitionClosedFromOpen = `-- name: SetVoteDefinitionClosedFromOpen :one
UPDATE vote_definitions
SET state = 'closed',
    closed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'open'
RETURNING id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at
`

func (q *Queries) SetVoteDefinitionClosedFromOpen(ctx context.Context, id int64) (VoteDefinition, error) {
	row := q.db.QueryRowContext(ctx, setVoteDefinitionClosedFromOpen, id)
	var i VoteDefinition
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgendaPointID,
		&i.MotionID,
		&i.Name,
		&i.Visibility,
		&i.State,
		&i.MinSelections,
		&i.MaxSelections,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setVoteDefinitionCountingFromOpen = `-- name: SetVoteDefinitionCountingFromOpen :one
UPDATE vote_definitions
SET state = 'counting',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'open'
RETURNING id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at
`

func (q *Queries) SetVoteDefinitionCountingFromOpen(ctx context.Context, id int64) (VoteDefinition, error) {
	row := q.db.QueryRowContext(ctx, setVoteDefinitionCountingFromOpen, id)
	var i VoteDefinition
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgendaPointID,
		&i.MotionID,
		&i.Name,
		&i.Visibility,
		&i.State,
		&i.MinSelections,
		&i.MaxSelections,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setVoteDefinitionOpen = `-- name: SetVoteDefinitionOpen :one
UPDATE vote_definitions
SET state = 'open',
    opened_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'draft'
RETURNING id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at
`

func (q *Queries) SetVoteDefinitionOpen(ctx context.Context, id int64) (VoteDefinition, error) {
	row := q.db.QueryRowContext(ctx, setVoteDefinitionOpen, id)
	var i VoteDefinition
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgendaPointID,
		&i.MotionID,
		&i.Name,
		&i.Visibility,
		&i.State,
		&i.MinSelections,
		&i.MaxSelections,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVoteDefinitionDraft = `-- name: UpdateVoteDefinitionDraft :one
UPDATE vote_definitions
SET meeting_id = ?,
    agenda_point_id = ?,
    motion_id = ?,
    name = ?,
    visibility = ?,
    min_selections = ?,
    max_selections = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'draft'
RETURNING id, meeting_id, agenda_point_id, motion_id, name, visibility, state, min_selections, max_selections, opened_at, closed_at, archived_at, created_at, updated_at
`

type UpdateVoteDefinitionDraftParams struct {
	MeetingID     int64
	AgendaPointID int64
	MotionID      sql.NullInt64
	Name          string
	Visibility    string
	MinSelections int64
	MaxSelections int64
	ID            int64
}

func (q *Queries) UpdateVoteDefinitionDraft(ctx context.Context, arg UpdateVoteDefinitionDraftParams) (VoteDefinition, error) {
	row := q.db.QueryRowContext(ctx, updateVoteDefinitionDraft,
		arg.MeetingID,
		arg.AgendaPointID,
		arg.MotionID,
		arg.Name,
		arg.Visibility,
		arg.MinSelections,
		arg.MaxSelections,
		arg.ID,
	)
	var i VoteDefinition
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgendaPointID,
		&i.MotionID,
		&i.Name,
		&i.Visibility,
		&i.State,
		&i.MinSelections,
		&i.MaxSelections,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
