// Code generated by route-codegen. DO NOT EDIT.

package paths

import (
	"context"
	"github.com/Y4shin/conference-tool/internal/locale"
	"net/url"
	"strings"
)

// Type-safe route builders
type Routes struct{}

var Route Routes

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdQuotationRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdQuotationRoute(slug string, meetingid string, agendapointid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdQuotationRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdQuotationRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdQuotationRoute) ManageAgendaPointSetQuotationPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/quotation"
}

func (Routes) LogoutSubmitPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/logout"
}

func (Routes) AdminCreateCommitteePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin/committee/create"
}

type CommitteeSlugMeetingMeetingIdQuotationRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdQuotationRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdQuotationRoute {
	return &CommitteeSlugMeetingMeetingIdQuotationRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdQuotationRoute) ManageMeetingSetQuotationPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/quotation"
}

type AdminCommitteeSlugUserCreateRoute struct {
	Slug string
}

func NewAdminCommitteeSlugUserCreateRoute(slug string) *AdminCommitteeSlugUserCreateRoute {
	return &AdminCommitteeSlugUserCreateRoute{
		Slug: slug,
	}
}

func (r *AdminCommitteeSlugUserCreateRoute) AdminCreateUserPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin/committee/" + r.Slug + "/user/create"
}

type AdminCommitteeSlugUserUserIdDeleteRoute struct {
	Slug   string
	UserId string
}

func NewAdminCommitteeSlugUserUserIdDeleteRoute(slug string, userid string) *AdminCommitteeSlugUserUserIdDeleteRoute {
	return &AdminCommitteeSlugUserUserIdDeleteRoute{
		Slug:   slug,
		UserId: userid,
	}
}

func (r *AdminCommitteeSlugUserUserIdDeleteRoute) AdminDeleteUserPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin/committee/" + r.Slug + "/user/" + r.UserId + "/delete"
}

type CommitteeSlugMeetingMeetingIdSpeakerAddCandidatesRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerAddCandidatesRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdSpeakerAddCandidatesRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerAddCandidatesRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerAddCandidatesRoute) ManageSpeakerAddCandidatesGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/add-candidates"
}

type ManageSpeakerAddCandidatesGetQueryParams struct {
	Q string
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerAddCandidatesRoute) ManageSpeakerAddCandidatesGetWithQuery(ctx context.Context, override string, q ManageSpeakerAddCandidatesGetQueryParams) string {
	path := r.ManageSpeakerAddCandidatesGet(ctx, override)
	var qparts []string
	if q.Q != "" {
		qparts = append(qparts, "q="+url.QueryEscape(q.Q))
	}
	if len(qparts) > 0 {
		path += "?" + strings.Join(qparts, "&")
	}
	return path
}

type CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdWithdrawRoute struct {
	Slug      string
	MeetingId string
	SpeakerId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerSpeakerIdWithdrawRoute(slug string, meetingid string, speakerid string) *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdWithdrawRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdWithdrawRoute{
		Slug:      slug,
		MeetingId: meetingid,
		SpeakerId: speakerid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdWithdrawRoute) ManageSpeakerWithdrawPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/" + r.SpeakerId + "/withdraw"
}

type CommitteeSlugMeetingMeetingIdManageJoinQrRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdManageJoinQrRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdManageJoinQrRoute {
	return &CommitteeSlugMeetingMeetingIdManageJoinQrRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdManageJoinQrRoute) CommitteeMeetingManageJoinQRGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/manage/join-qr"
}

type CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdStartRoute struct {
	Slug      string
	MeetingId string
	SpeakerId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerSpeakerIdStartRoute(slug string, meetingid string, speakerid string) *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdStartRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdStartRoute{
		Slug:      slug,
		MeetingId: meetingid,
		SpeakerId: speakerid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdStartRoute) ManageSpeakerStartPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/" + r.SpeakerId + "/start"
}

type CommitteeSlugMeetingMeetingIdAttendeeLoginRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdAttendeeLoginRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdAttendeeLoginRoute {
	return &CommitteeSlugMeetingMeetingIdAttendeeLoginRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAttendeeLoginRoute) AttendeeLoginPageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/attendee-login"
}

func (r *CommitteeSlugMeetingMeetingIdAttendeeLoginRoute) AttendeeLoginSubmitPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/attendee-login"
}

func (Routes) LoginSubmitPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/login"
}

type CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdRemoveRoute struct {
	Slug      string
	MeetingId string
	SpeakerId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerSpeakerIdRemoveRoute(slug string, meetingid string, speakerid string) *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdRemoveRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdRemoveRoute{
		Slug:      slug,
		MeetingId: meetingid,
		SpeakerId: speakerid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdRemoveRoute) ManageSpeakerRemovePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/" + r.SpeakerId + "/remove"
}

type CommitteeSlugMeetingMeetingIdProtocolRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdProtocolRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdProtocolRoute {
	return &CommitteeSlugMeetingMeetingIdProtocolRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdProtocolRoute) MeetingProtocolPageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/protocol"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdDeleteRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
	MotionId      string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdDeleteRoute(slug string, meetingid string, agendapointid string, motionid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdDeleteRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdDeleteRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
		MotionId:      motionid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdDeleteRoute) ManageMotionDeletePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/motion/" + r.MotionId + "/delete"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdVoteRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
	MotionId      string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdVoteRoute(slug string, meetingid string, agendapointid string, motionid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdVoteRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdVoteRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
		MotionId:      motionid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionMotionIdVoteRoute) ManageMotionRecordVotePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/motion/" + r.MotionId + "/vote"
}

type CommitteeSlugMeetingMeetingIdSpeakerAddRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerAddRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdSpeakerAddRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerAddRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerAddRoute) ManageSpeakerAddPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/add"
}

type CommitteeSlugMeetingMeetingIdSpeakersStreamRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakersStreamRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdSpeakersStreamRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakersStreamRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakersStreamRoute) AttendeeSpeakersStreamGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speakers/stream"
}

type CommitteeSlugMeetingMeetingIdSpeakerSelfAddRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerSelfAddRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdSpeakerSelfAddRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerSelfAddRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerSelfAddRoute) AttendeeSpeakerSelfAddPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/self-add"
}

func (Routes) LoginPageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentCreateRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentCreateRoute(slug string, meetingid string, agendapointid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentCreateRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentCreateRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentCreateRoute) ManageAttachmentCreatePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/attachment/create"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdToolsRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdToolsRoute(slug string, meetingid string, agendapointid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdToolsRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdToolsRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdToolsRoute) ManageAgendaPointToolsPageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/tools"
}

type CommitteeSlugMeetingMeetingIdModeratorRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdModeratorRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdModeratorRoute {
	return &CommitteeSlugMeetingMeetingIdModeratorRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdModeratorRoute) ManageMeetingSetModeratorPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/moderator"
}

type CommitteeSlugMeetingMeetingIdSpeakerSelfYieldRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerSelfYieldRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdSpeakerSelfYieldRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerSelfYieldRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerSelfYieldRoute) AttendeeSpeakerSelfYieldPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/self-yield"
}

func (Routes) AdminLogoutPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin/logout"
}

type CommitteeSlugMeetingMeetingIdManageRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdManageRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdManageRoute {
	return &CommitteeSlugMeetingMeetingIdManageRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdManageRoute) CommitteeMeetingManageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/manage"
}

type CommitteeSlugMeetingMeetingIdBlobBlobIdRoute struct {
	Slug      string
	MeetingId string
	BlobId    string
}

func NewCommitteeSlugMeetingMeetingIdBlobBlobIdRoute(slug string, meetingid string, blobid string) *CommitteeSlugMeetingMeetingIdBlobBlobIdRoute {
	return &CommitteeSlugMeetingMeetingIdBlobBlobIdRoute{
		Slug:      slug,
		MeetingId: meetingid,
		BlobId:    blobid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdBlobBlobIdRoute) ServeBlobDownloadGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/blob/" + r.BlobId + ""
}

type CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdDeleteRoute struct {
	Slug       string
	MeetingId  string
	AttendeeId string
}

func NewCommitteeSlugMeetingMeetingIdAttendeeAttendeeIdDeleteRoute(slug string, meetingid string, attendeeid string) *CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdDeleteRoute {
	return &CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdDeleteRoute{
		Slug:       slug,
		MeetingId:  meetingid,
		AttendeeId: attendeeid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdDeleteRoute) ManageAttendeeDeletePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/attendee/" + r.AttendeeId + "/delete"
}

type CommitteeSlugMeetingMeetingIdJoinRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdJoinRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdJoinRoute {
	return &CommitteeSlugMeetingMeetingIdJoinRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdJoinRoute) MeetingJoinPageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/join"
}

func (r *CommitteeSlugMeetingMeetingIdJoinRoute) MeetingJoinSubmitPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/join"
}

type CommitteeSlugMeetingMeetingIdProtocolAgendaPointIdRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
}

func NewCommitteeSlugMeetingMeetingIdProtocolAgendaPointIdRoute(slug string, meetingid string, agendapointid string) *CommitteeSlugMeetingMeetingIdProtocolAgendaPointIdRoute {
	return &CommitteeSlugMeetingMeetingIdProtocolAgendaPointIdRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdProtocolAgendaPointIdRoute) ProtocolSaveAgendaPointPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/protocol/" + r.AgendaPointId + ""
}

type CommitteeSlugMeetingMeetingIdAttendeeCreateRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdAttendeeCreateRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdAttendeeCreateRoute {
	return &CommitteeSlugMeetingMeetingIdAttendeeCreateRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAttendeeCreateRoute) ManageAttendeeCreatePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/attendee/create"
}

type CommitteeSlugMeetingMeetingIdGuestRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdGuestRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdGuestRoute {
	return &CommitteeSlugMeetingMeetingIdGuestRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdGuestRoute) MeetingGuestSignupPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/guest"
}

type AdminCommitteeSlugDeleteRoute struct {
	Slug string
}

func NewAdminCommitteeSlugDeleteRoute(slug string) *AdminCommitteeSlugDeleteRoute {
	return &AdminCommitteeSlugDeleteRoute{
		Slug: slug,
	}
}

func (r *AdminCommitteeSlugDeleteRoute) AdminDeleteCommitteePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin/committee/" + r.Slug + "/delete"
}

type AdminCommitteeSlugRoute struct {
	Slug string
}

func NewAdminCommitteeSlugRoute(slug string) *AdminCommitteeSlugRoute {
	return &AdminCommitteeSlugRoute{
		Slug: slug,
	}
}

func (r *AdminCommitteeSlugRoute) AdminCommitteeUsersGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin/committee/" + r.Slug + ""
}

type AdminCommitteeUsersGetQueryParams struct {
	Page     string
	PageSize string
}

func (r *AdminCommitteeSlugRoute) AdminCommitteeUsersGetWithQuery(ctx context.Context, override string, q AdminCommitteeUsersGetQueryParams) string {
	path := r.AdminCommitteeUsersGet(ctx, override)
	var qparts []string
	if q.Page != "" {
		qparts = append(qparts, "page="+url.QueryEscape(q.Page))
	}
	if q.PageSize != "" {
		qparts = append(qparts, "page_size="+url.QueryEscape(q.PageSize))
	}
	if len(qparts) > 0 {
		path += "?" + strings.Join(qparts, "&")
	}
	return path
}

type CommitteeSlugMeetingMeetingIdAgendaPointCreateRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointCreateRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdAgendaPointCreateRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointCreateRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointCreateRoute) ManageAgendaPointCreatePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/create"
}

type CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdEndRoute struct {
	Slug      string
	MeetingId string
	SpeakerId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerSpeakerIdEndRoute(slug string, meetingid string, speakerid string) *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdEndRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdEndRoute{
		Slug:      slug,
		MeetingId: meetingid,
		SpeakerId: speakerid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdEndRoute) ManageSpeakerEndPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/" + r.SpeakerId + "/end"
}

type CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdPriorityRoute struct {
	Slug      string
	MeetingId string
	SpeakerId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakerSpeakerIdPriorityRoute(slug string, meetingid string, speakerid string) *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdPriorityRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdPriorityRoute{
		Slug:      slug,
		MeetingId: meetingid,
		SpeakerId: speakerid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakerSpeakerIdPriorityRoute) ManageSpeakerTogglePriorityPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speaker/" + r.SpeakerId + "/priority"
}

type CommitteeSlugMeetingMeetingIdSpeakersPartialRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdSpeakersPartialRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdSpeakersPartialRoute {
	return &CommitteeSlugMeetingMeetingIdSpeakersPartialRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSpeakersPartialRoute) ManageSpeakersListPartialGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/speakers/partial"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionCreateRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionCreateRoute(slug string, meetingid string, agendapointid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionCreateRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionCreateRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdMotionCreateRoute) ManageMotionCreatePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/motion/create"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentAttachmentIdDeleteRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
	AttachmentId  string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentAttachmentIdDeleteRoute(slug string, meetingid string, agendapointid string, attachmentid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentAttachmentIdDeleteRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentAttachmentIdDeleteRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
		AttachmentId:  attachmentid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdAttachmentAttachmentIdDeleteRoute) ManageAttachmentDeletePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/attachment/" + r.AttachmentId + "/delete"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdDeleteRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdDeleteRoute(slug string, meetingid string, agendapointid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdDeleteRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdDeleteRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdDeleteRoute) ManageAgendaPointDeletePost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/delete"
}

func (Routes) AdminDashboardGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin"
}

type AdminDashboardGetQueryParams struct {
	Page     string
	PageSize string
}

func (Routes) AdminDashboardGetWithQuery(ctx context.Context, override string, q AdminDashboardGetQueryParams) string {
	path := locale.PathPrefix(ctx, override) + "/admin"
	var qparts []string
	if q.Page != "" {
		qparts = append(qparts, "page="+url.QueryEscape(q.Page))
	}
	if q.PageSize != "" {
		qparts = append(qparts, "page_size="+url.QueryEscape(q.PageSize))
	}
	if len(qparts) > 0 {
		path += "?" + strings.Join(qparts, "&")
	}
	return path
}

type CommitteeSlugMeetingMeetingIdProtocolWriterRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdProtocolWriterRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdProtocolWriterRoute {
	return &CommitteeSlugMeetingMeetingIdProtocolWriterRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdProtocolWriterRoute) ManageSetProtocolWriterPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/protocol-writer"
}

type CommitteeSlugMeetingMeetingIdAttendeeSelfSignupRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdAttendeeSelfSignupRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdAttendeeSelfSignupRoute {
	return &CommitteeSlugMeetingMeetingIdAttendeeSelfSignupRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAttendeeSelfSignupRoute) ManageAttendeeSelfSignupPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/attendee/self-signup"
}

type CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdChairRoute struct {
	Slug       string
	MeetingId  string
	AttendeeId string
}

func NewCommitteeSlugMeetingMeetingIdAttendeeAttendeeIdChairRoute(slug string, meetingid string, attendeeid string) *CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdChairRoute {
	return &CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdChairRoute{
		Slug:       slug,
		MeetingId:  meetingid,
		AttendeeId: attendeeid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdChairRoute) ManageAttendeeToggleChairPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/attendee/" + r.AttendeeId + "/chair"
}

type CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdRecoveryRoute struct {
	Slug       string
	MeetingId  string
	AttendeeId string
}

func NewCommitteeSlugMeetingMeetingIdAttendeeAttendeeIdRecoveryRoute(slug string, meetingid string, attendeeid string) *CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdRecoveryRoute {
	return &CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdRecoveryRoute{
		Slug:       slug,
		MeetingId:  meetingid,
		AttendeeId: attendeeid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAttendeeAttendeeIdRecoveryRoute) ManageAttendeeRecoveryPageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/attendee/" + r.AttendeeId + "/recovery"
}

type CommitteeSlugMeetingMeetingIdLiveRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdLiveRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdLiveRoute {
	return &CommitteeSlugMeetingMeetingIdLiveRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdLiveRoute) MeetingLiveLegacyRedirectGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/live"
}

type CommitteeSlugMeetingCreateRoute struct {
	Slug string
}

func NewCommitteeSlugMeetingCreateRoute(slug string) *CommitteeSlugMeetingCreateRoute {
	return &CommitteeSlugMeetingCreateRoute{
		Slug: slug,
	}
}

func (r *CommitteeSlugMeetingCreateRoute) CommitteeCreateMeetingPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/create"
}

type CommitteeSlugMeetingMeetingIdSettingsPartialRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdSettingsPartialRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdSettingsPartialRoute {
	return &CommitteeSlugMeetingMeetingIdSettingsPartialRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSettingsPartialRoute) ManageMeetingSettingsPartialGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/settings/partial"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdActivateRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdActivateRoute(slug string, meetingid string, agendapointid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdActivateRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdActivateRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdActivateRoute) ManageActivateAgendaPointPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/activate"
}

type CommitteeSlugMeetingMeetingIdDeleteRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdDeleteRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdDeleteRoute {
	return &CommitteeSlugMeetingMeetingIdDeleteRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdDeleteRoute) CommitteeDeleteMeetingPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/delete"
}

type CommitteeSlugMeetingMeetingIdRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdRoute {
	return &CommitteeSlugMeetingMeetingIdRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdRoute) MeetingLivePageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + ""
}

type CommitteeSlugMeetingMeetingIdSignupOpenRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdSignupOpenRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdSignupOpenRoute {
	return &CommitteeSlugMeetingMeetingIdSignupOpenRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdSignupOpenRoute) ManageToggleSignupOpenPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/signup-open"
}

type CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdModeratorRoute struct {
	Slug          string
	MeetingId     string
	AgendaPointId string
}

func NewCommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdModeratorRoute(slug string, meetingid string, agendapointid string) *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdModeratorRoute {
	return &CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdModeratorRoute{
		Slug:          slug,
		MeetingId:     meetingid,
		AgendaPointId: agendapointid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdAgendaPointAgendaPointIdModeratorRoute) ManageAgendaPointSetModeratorPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/agenda-point/" + r.AgendaPointId + "/moderator"
}

type CommitteeSlugMeetingMeetingIdActivateRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdActivateRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdActivateRoute {
	return &CommitteeSlugMeetingMeetingIdActivateRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdActivateRoute) CommitteeActivateMeetingPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/activate"
}

func (Routes) AdminLoginGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin/login"
}
func (Routes) AdminLoginSubmitPost(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/admin/login"
}

type CommitteeSlugRoute struct {
	Slug string
}

func NewCommitteeSlugRoute(slug string) *CommitteeSlugRoute {
	return &CommitteeSlugRoute{
		Slug: slug,
	}
}

func (r *CommitteeSlugRoute) CommitteePageGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + ""
}

type CommitteePageGetQueryParams struct {
	Page     string
	PageSize string
}

func (r *CommitteeSlugRoute) CommitteePageGetWithQuery(ctx context.Context, override string, q CommitteePageGetQueryParams) string {
	path := r.CommitteePageGet(ctx, override)
	var qparts []string
	if q.Page != "" {
		qparts = append(qparts, "page="+url.QueryEscape(q.Page))
	}
	if q.PageSize != "" {
		qparts = append(qparts, "page_size="+url.QueryEscape(q.PageSize))
	}
	if len(qparts) > 0 {
		path += "?" + strings.Join(qparts, "&")
	}
	return path
}

type CommitteeSlugMeetingMeetingIdManageStreamRoute struct {
	Slug      string
	MeetingId string
}

func NewCommitteeSlugMeetingMeetingIdManageStreamRoute(slug string, meetingid string) *CommitteeSlugMeetingMeetingIdManageStreamRoute {
	return &CommitteeSlugMeetingMeetingIdManageStreamRoute{
		Slug:      slug,
		MeetingId: meetingid,
	}
}

func (r *CommitteeSlugMeetingMeetingIdManageStreamRoute) ManageStreamGet(ctx context.Context, override string) string {
	return locale.PathPrefix(ctx, override) + "/committee/" + r.Slug + "/meeting/" + r.MeetingId + "/manage/stream"
}

type ManageStreamGetQueryParams struct {
	ClientId string
}

func (r *CommitteeSlugMeetingMeetingIdManageStreamRoute) ManageStreamGetWithQuery(ctx context.Context, override string, q ManageStreamGetQueryParams) string {
	path := r.ManageStreamGet(ctx, override)
	var qparts []string
	if q.ClientId != "" {
		qparts = append(qparts, "client_id="+url.QueryEscape(q.ClientId))
	}
	if len(qparts) > 0 {
		path += "?" + strings.Join(qparts, "&")
	}
	return path
}

func (Routes) HtmxExtSseMinJs() string {
	return "/static/htmx-ext-sse.min.js"
}

func (Routes) HtmxMinJs() string {
	return "/static/htmx.min.js"
}
