// Code generated by route-codegen. DO NOT EDIT.

package paths

// Type-safe route builders
type Routes struct{}

var Route Routes

type AdminCommitteeSlugDeleteRoute struct {
	Slug string
}

func NewAdminCommitteeSlugDeleteRoute(slug string) *AdminCommitteeSlugDeleteRoute {
	return &AdminCommitteeSlugDeleteRoute{
		Slug: slug,
	}
}

func (r *AdminCommitteeSlugDeleteRoute) AdminDeleteCommitteePost() string {
	return "/admin/committee/" + r.Slug + "/delete"
}

type AdminCommitteeSlugRoute struct {
	Slug string
}

func NewAdminCommitteeSlugRoute(slug string) *AdminCommitteeSlugRoute {
	return &AdminCommitteeSlugRoute{
		Slug: slug,
	}
}

func (r *AdminCommitteeSlugRoute) AdminCommitteeUsersGet() string {
	return "/admin/committee/" + r.Slug + ""
}

type AdminCommitteeSlugUserCreateRoute struct {
	Slug string
}

func NewAdminCommitteeSlugUserCreateRoute(slug string) *AdminCommitteeSlugUserCreateRoute {
	return &AdminCommitteeSlugUserCreateRoute{
		Slug: slug,
	}
}

func (r *AdminCommitteeSlugUserCreateRoute) AdminCreateUserPost() string {
	return "/admin/committee/" + r.Slug + "/user/create"
}

func (Routes) LogoutSubmitPost() string {
	return "/logout"
}

func (Routes) AdminLogoutPost() string {
	return "/admin/logout"
}

type AdminCommitteeSlugUserUserIdDeleteRoute struct {
	Slug   string
	UserId string
}

func NewAdminCommitteeSlugUserUserIdDeleteRoute(slug string, userid string) *AdminCommitteeSlugUserUserIdDeleteRoute {
	return &AdminCommitteeSlugUserUserIdDeleteRoute{
		Slug:   slug,
		UserId: userid,
	}
}

func (r *AdminCommitteeSlugUserUserIdDeleteRoute) AdminDeleteUserPost() string {
	return "/admin/committee/" + r.Slug + "/user/" + r.UserId + "/delete"
}

func (Routes) LoginPageGet() string {
	return "/"
}

func (Routes) LoginSubmitPost() string {
	return "/login"
}

type CommitteeSlugRoute struct {
	Slug string
}

func NewCommitteeSlugRoute(slug string) *CommitteeSlugRoute {
	return &CommitteeSlugRoute{
		Slug: slug,
	}
}

func (r *CommitteeSlugRoute) CommitteePageGet() string {
	return "/committee/" + r.Slug + ""
}

type CommitteeSlugMeetingCreateRoute struct {
	Slug string
}

func NewCommitteeSlugMeetingCreateRoute(slug string) *CommitteeSlugMeetingCreateRoute {
	return &CommitteeSlugMeetingCreateRoute{
		Slug: slug,
	}
}

func (r *CommitteeSlugMeetingCreateRoute) CommitteeCreateMeetingPost() string {
	return "/committee/" + r.Slug + "/meeting/create"
}

func (Routes) AdminLoginGet() string {
	return "/admin/login"
}
func (Routes) AdminLoginSubmitPost() string {
	return "/admin/login"
}

func (Routes) AdminDashboardGet() string {
	return "/admin"
}

func (Routes) AdminCreateCommitteePost() string {
	return "/admin/committee/create"
}

func (Routes) HtmxExtSseMinJs() string {
	return "/static/htmx-ext-sse.min.js"
}

func (Routes) HtmxMinJs() string {
	return "/static/htmx.min.js"
}
