version: 1.0

middleware_groups: []

routes:
  - path: /
    methods:
      - verb: GET
        handler: HomePage
        template:
          package: github.com/Y4shin/conference-tool/internal/templates
          type: HomePageTemplate
          input_type: HomePageInput

  - path: /increment
    methods:
      - verb: POST
        handler: Increment
        template:
          package: github.com/Y4shin/conference-tool/internal/templates
          type: CounterTemplate
          input_type: CounterInput

  - path: /subscribe
    methods:
      - verb: GET
        handler: Subscribe
        sse: true
