// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AppShell() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:"Space Grotesk", "Avenir Next", "Segoe UI", sans-serif;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:radial-gradient(circle at 18% 0%, #112a53 0%, #0a1937 38%, #070f25 100%);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#eaf2ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:100vh;`)
	templ_7745c5c3_CSSID := templ.CSSID(`AppShell`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func PageHeader() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:linear-gradient(90deg, #071126 0%, #0b1e3f 52%, #102a56 100%);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#f2f8ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-bottom:1px solid #16355f;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:1rem 1.25rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`PageHeader`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func PageMain() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`max-width:1200px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0 auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:1.25rem 1.25rem 1.7rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`PageMain`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func PageFooter() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`max-width:1200px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0 auto;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0 1.25rem 1.25rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`PageFooter`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func Panel() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:linear-gradient(170deg, rgba(8, 22, 50, 0.94), rgba(5, 17, 39, 0.97));`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid rgba(80, 125, 183, 0.38);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:16px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-bottom:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`box-shadow:inset 0 1px 0 rgba(170, 217, 255, 0.06);`)
	templ_7745c5c3_CSSID := templ.CSSID(`Panel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func DataTable() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:100%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-collapse:collapse;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(4, 14, 34, 0.62);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#eaf2ff;`)
	templ_7745c5c3_CSSID := templ.CSSID(`DataTable`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func InlineForm() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline;`)
	templ_7745c5c3_CSSID := templ.CSSID(`InlineForm`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LanguageSwitcherWrap() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.3rem 0.55rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:999px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(6, 18, 42, 0.72);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid rgba(96, 155, 232, 0.35);`)
	templ_7745c5c3_CSSBuilder.WriteString(`backdrop-filter:blur(8px);`)
	templ_7745c5c3_CSSID := templ.CSSID(`LanguageSwitcherWrap`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LanguageSwitcherLink() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`color:#98d6ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-decoration:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:600;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LanguageSwitcherLink`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func FullWidthField() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`width:100%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`max-width:100%;`)
	templ_7745c5c3_CSSID := templ.CSSID(`FullWidthField`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func ErrorText() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(135, 21, 42, 0.28);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid rgba(246, 112, 143, 0.52);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:8px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#ffd2de;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.55rem 0.7rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-bottom:0.8rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`ErrorText`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func ManageGrid() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`grid-template-columns:repeat(auto-fit, minmax(340px, 1fr));`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:start;`)
	templ_7745c5c3_CSSID := templ.CSSID(`ManageGrid`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func ManageGridSlice() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:contents;`)
	templ_7745c5c3_CSSID := templ.CSSID(`ManageGridSlice`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBody() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:radial-gradient(circle at 18% 0%, #112a53 0%, #0a1937 38%, #070f25 100%);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#eaf2ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:"Space Grotesk", "Avenir Next", "Segoe UI", sans-serif;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:100vh;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBody`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveHeader() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:flex-start;`)
	templ_7745c5c3_CSSBuilder.WriteString(`justify-content:space-between;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:linear-gradient(90deg, #071126 0%, #0b1e3f 52%, #102a56 100%);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#f2f8ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-bottom:1px solid #16355f;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveHeader`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveUserBar() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.85rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.92rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveUserBar`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveLogoutButton() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(11, 172, 255, 0.18);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#dcf5ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid #21b3ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:999px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.4rem 0.85rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`cursor:pointer;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveLogoutButton`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveManageLink() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:999px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid #21b3ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(11, 172, 255, 0.12);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#dcf5ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-decoration:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.85rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:600;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.38rem 0.75rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveManageLink`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveGrid() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:grid;`)
	templ_7745c5c3_CSSBuilder.WriteString(`grid-template-columns:minmax(0, 1.15fr) minmax(0, 1fr);`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:1rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveGrid`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LivePanel() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:linear-gradient(170deg, rgba(8, 22, 50, 0.94), rgba(5, 17, 39, 0.97));`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid rgba(80, 125, 183, 0.38);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:18px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#eaf2ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:520px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`box-shadow:inset 0 1px 0 rgba(170, 217, 255, 0.06);`)
	templ_7745c5c3_CSSID := templ.CSSID(`LivePanel`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveAgendaList() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`list-style:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-direction:column;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.45rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveAgendaList`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveAgendaItem() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.55rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:baseline;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.55rem 0.75rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(4, 14, 34, 0.78);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid rgba(40, 87, 148, 0.48);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:10px;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveAgendaItem`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveAgendaItemActive() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`border-color:#1bbaff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`box-shadow:0 0 0 1px rgba(27, 186, 255, 0.4);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#6dd8ff;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveAgendaItemActive`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveAgendaSubPoint() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`margin-left:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`opacity:0.92;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveAgendaSubPoint`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveAgendaPosition() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.95rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:700;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#8cb9ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:2.4rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveAgendaPosition`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveAgendaTitle() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:1.2rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`line-height:1.25;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveAgendaTitle`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveActiveAgendaTitle() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0 0 0.8rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:1.35rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:700;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#9cd9ff;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveActiveAgendaTitle`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveEmptyState() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`margin:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#b3c7e6;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveEmptyState`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerTable() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:transparent;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerTable`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerHead() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`text-align:left;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.82rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:700;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#84a4d0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0 0.4rem 0.45rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-bottom:1px solid rgba(84, 124, 183, 0.45);`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerHead`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerRow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`border-bottom:1px solid rgba(71, 103, 148, 0.28);`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerRow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerCellName() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:clamp(1.25rem, 2.7vw, 3rem);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:800;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.55rem 0.45rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#edf5ff;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerCellName`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerCellMeta() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.92rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#9ebce1;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.55rem 0.45rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-transform:uppercase;`)
	templ_7745c5c3_CSSBuilder.WriteString(`letter-spacing:0.05em;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerCellMeta`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerCellSmall() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.9rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:700;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#7faee8;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.55rem 0.45rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`vertical-align:baseline;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerCellSmall`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeaking() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(17, 128, 197, 0.17);`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeaking`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveMyTurn() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`outline:1px dashed rgba(148, 223, 255, 0.4);`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveMyTurn`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBottomBar() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`position:fixed;`)
	templ_7745c5c3_CSSBuilder.WriteString(`left:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`right:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`bottom:0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`justify-content:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.35rem 0.5rem 0.45rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`pointer-events:none;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBottomBar`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveLanguageDock() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`pointer-events:auto;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveLanguageDock`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerList() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-direction:column;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.55rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerList`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerItem() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.7rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:flex-start;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(8, 22, 50, 0.64);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid rgba(74, 117, 174, 0.36);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:12px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.65rem 0.75rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerItem`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerOrder() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`min-width:2.2rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:1rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:700;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#9bc5ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding-top:0.2rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerOrder`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerMain() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-direction:column;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.25rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex:1;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerMain`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerName() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:clamp(1.2rem, 2.5vw, 2.9rem);`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:800;`)
	templ_7745c5c3_CSSBuilder.WriteString(`line-height:1.06;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#edf5ff;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerName`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerMetaRow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.6rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-wrap:wrap;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerMetaRow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakerType() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.77rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#9ebce1;`)
	templ_7745c5c3_CSSBuilder.WriteString(`text-transform:uppercase;`)
	templ_7745c5c3_CSSBuilder.WriteString(`letter-spacing:0.08em;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakerType`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBadgeRow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.35rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-wrap:wrap;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBadgeRow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBadge() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:inline-flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:0.7rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:700;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.15rem 0.45rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:999px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid rgba(146, 183, 229, 0.45);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#d4e8ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(18, 37, 70, 0.75);`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBadge`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBadgeROPM() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`border-color:rgba(79, 214, 255, 0.8);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#7de7ff;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBadgeROPM`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBadgeQuoted() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`border-color:rgba(216, 164, 255, 0.85);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#efcfff;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBadgeQuoted`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBadgeFirst() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`border-color:rgba(153, 255, 197, 0.85);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#b7ffd7;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBadgeFirst`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBadgePriority() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`border-color:rgba(255, 205, 112, 0.88);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#ffdea1;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBadgePriority`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveBadgeModerator() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`border-color:rgba(111, 215, 255, 0.9);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#c5f1ff;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveBadgeModerator`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSpeakersHeaderRow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`justify-content:space-between;`)
	templ_7745c5c3_CSSBuilder.WriteString(`align-items:center;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-bottom:0.5rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSpeakersHeaderRow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSelfAddRow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`gap:0.5rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-wrap:wrap;`)
	templ_7745c5c3_CSSBuilder.WriteString(`margin-top:0.8rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSelfAddRow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func LiveSelfAddButton() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background:rgba(11, 172, 255, 0.16);`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#ddf6ff;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:1px solid rgba(84, 214, 255, 0.7);`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:10px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:0.38rem 0.72rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:600;`)
	templ_7745c5c3_CSSBuilder.WriteString(`cursor:pointer;`)
	templ_7745c5c3_CSSID := templ.CSSID(`LiveSelfAddButton`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func GlobalStylesheetLink() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<link rel=\"stylesheet\" href=\"/styles/templ.css\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func GlobalCSSClasses() []templ.CSSClass {
	return []templ.CSSClass{
		AppShell(),
		PageHeader(),
		PageMain(),
		PageFooter(),
		Panel(),
		DataTable(),
		InlineForm(),
		LanguageSwitcherWrap(),
		LanguageSwitcherLink(),
		FullWidthField(),
		ErrorText(),
		ManageGrid(),
		ManageGridSlice(),
		LiveBody(),
		LiveHeader(),
		LiveUserBar(),
		LiveLogoutButton(),
		LiveManageLink(),
		LiveGrid(),
		LivePanel(),
		LiveAgendaList(),
		LiveAgendaItem(),
		LiveAgendaItemActive(),
		LiveAgendaSubPoint(),
		LiveAgendaPosition(),
		LiveAgendaTitle(),
		LiveActiveAgendaTitle(),
		LiveEmptyState(),
		LiveSpeakerTable(),
		LiveSpeakerHead(),
		LiveSpeakerRow(),
		LiveSpeakerCellName(),
		LiveSpeakerCellMeta(),
		LiveSpeakerCellSmall(),
		LiveSpeaking(),
		LiveMyTurn(),
		LiveBottomBar(),
		LiveLanguageDock(),
		LiveSpeakerList(),
		LiveSpeakerItem(),
		LiveSpeakerOrder(),
		LiveSpeakerMain(),
		LiveSpeakerName(),
		LiveSpeakerMetaRow(),
		LiveSpeakerType(),
		LiveBadgeRow(),
		LiveBadge(),
		LiveBadgeROPM(),
		LiveBadgeQuoted(),
		LiveBadgeFirst(),
		LiveBadgePriority(),
		LiveBadgeModerator(),
		LiveSpeakersHeaderRow(),
		LiveSelfAddRow(),
		LiveSelfAddButton(),
	}
}

var _ = templruntime.GeneratedTemplate
